---
name: 🐞 Bug report
description: File a bug/issue
title: "[BUG]: <title>"
labels: ["possible bug"]
assignees: mmalyska
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: dropdown
    id: os-running-on
    attributes:
      label: What os you're running application on?
      options:
        - 'Linux'
        - 'MacOS'
        - 'Windows'
    validations:
      required: true

  - type: input
    id: version-running
    attributes:
      label: What version of application you are running?
    validations:
      required: false

  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: 'A clear and concise description of what the bug is.'
    validations:
      required: true

  - type: textarea
    id: example-manifests
    attributes:
      label: Example manifest that is not working
      description: |
        Paste faulty manifest and example secret file
      value: |
        <details><summary>Manifest</summary>
        ```
        Copy/paste manifests here, between the starting and ending backticks
        ```
        </details>

        Tip: You can also attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
