blank_issues_enabled: false
contact_links:
  - name: Replacer Community Support
    url: https://github.com/mmalyska/argocd-secret-replacer/discussions/new
    about: Please ask and answer questions here.
