---
name: Feature request
description: Suggest an idea for this project
title: "[FEATURE]: <title>"
labels: ['enhancement']
assignees: mmalyska
body:
  - type: textarea
    id: what-would-you-like-to-add
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: implementation-idea-textbox
    attributes:
      label: Describe the solution you'd like
      description: |
        A clear and concise description of what you want to happen.
        A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
