---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argocd

namespace: argocd

resources:
  - https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.6.7
  - resources/sops-age-secret.yaml
  - resources/sops-replacer-plugin.yaml

patchesStrategicMerge:
  - patches/argo-cd-repo-server.yaml
