---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argocd

namespace: argocd

resources:
  - https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.4.11
  - resources/sops-age-secret.yaml

patchesStrategicMerge:
  - patches/argocd-cm.yaml
  - patches/argo-cd-repo-server.yaml
